modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/shedaniel/architectury/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "architectury"
version = "4.11.93"
displayName = "Architectury"
authors = "shedaniel"
description = '''
A intermediary api aimed to ease developing multiplatform mods.
'''
logoFile = "icon.png"
license = "LGPL-3"

[[dependencies.architectury]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.architectury]]
modId = "forge"
mandatory = true
versionRange = "[40.1.14,)"
ordering = "NONE"
side = "BOTH"
