modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/mekanism/Mekanism/issues"
license="MIT"

[[mods]]
    modId="mekanism"
    version="10.2.5"
    displayName="Mekanism"
    displayURL="https://aidancbrady.com/mekanism/"
    authors="Aidancbrady, Thommy101, Thiakil, pupnewfster, dizzyd"
    credits="unpairedbracket, CyanideX, Ridanisaurus and many others"
    logoFile="logo.png"
    description='''Mekanism is a Minecraft add-on featuring high-tech machinery that can be used to create powerful tools, armor, and weapons.'''

[[dependencies.mekanism]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    side="BOTH"
[[dependencies.mekanism]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.27,)"
    side="BOTH"
[[dependencies.mekanism]]
    modId="crafttweaker"
    mandatory=false
    versionRange="[9.1.139,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.mekanism]]
    modId="jei"
    mandatory=false
    versionRange="[9.7.0.180,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.mekanism]]
    modId="wildfire_gender"
    mandatory=false
    versionRange="[2.9,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.mekanism]]
    modId="curios"
    mandatory=false
    versionRange="[1.18.2-5.0.6.3,)"
    ordering="AFTER"
    side="BOTH"